name: Giveway
favicon: null
layout_spectrum: 0.24572
typography_spectrum: 0.4119139083195478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1f1f1f'
    - '#696969'
    - '#fb8628'
    - '#84b0dd'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.6518640262074769
  rhythmicContrast: 0.9952934531029314
purpose: []
